version: '2.1'

services:
  azure-ts-qs:
    image: azure-ts-qs
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js